version: "3"
services:
  ccv:
    build: .
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: viewer.ccv.docker
      VIRTUAL_PORT: 3300
    volumes:
      - .:/usr/src/app
      - ccv_node_modules:/usr/src/app/node_modules

volumes:
  ccv_node_modules: {}
